In [ ]:
#Importando a biblioteca Pandas e Numpy
import pandas as pd
import numpy as np

In [ ]:
# Carregando dataset
# Importa a biblioteca 'drive' do módulo 'google.colab' para interagir com o Google Drive.
from google.colab import drive
# Monta o Google Drive no diretório '/content/drive' para acessar arquivos armazenados nele.
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os # Importa o módulo 'os' para interagir com o sistema operacional, como listar diretórios.

# Define o caminho para a raiz do Google Drive.
drive_root = '/content/drive/MyDrive/'

# Verifica se o caminho do Google Drive existe.
if os.path.exists(drive_root):
    print(f"Conteúdo de {drive_root}:")
    # Lista e imprime o conteúdo do diretório raiz do Google Drive.
    for item in os.listdir(drive_root):
        print(item)
else:
    print(f"O caminho {drive_root} não foi encontrado. Por favor, certifique-se de que o Google Drive está montado corretamente.")

Conteúdo de /content/drive/MyDrive/:
IMPTIMIR POLI.oxps
Fundamentos_Da_Fisica_V4_[Halliday].pdf
IMG-20170504-WA0027.jpeg
IMG-20170529-WA0170.jpeg
12800_1_SEMESTRE_MAT.pdf
Precisão de medidas com o uso de Paquímetro e Micrômetro(Parcial 8)-T1FE1- Engenharia Eletrônica.docx
Relatorio novo 2.1.docx
Fatura_082018_GABRIELA_5262_MASTER_00099186811291.PDF
Cópia de Capítulo 2 - T4ED2 rev 6.pdf
PERIMED - Laser Speckle Contrast Analysis.docx
20191004_190503.mp4
20191219143133.jpg
logo ifsp.png
UTILIZAÇÃO DO BIOSPECKLE LASER NA AVALIAÇÃO DO POTENCIAL GERMINATIVO DE SEMENTES DE IPÊ ROXO.pdf
QUANDO O RUIDO TORNOU SE INFORMAÇÃO.pdf
SÊMEN BOVINO E BIOSPECKLE.pdf
FREQUENCY SIGNATURE OF WATER ACTIVITY BY BIOSPECKLE LASER .pdf
EM FALTA.docx
FREQUENCY SIGNATURE OF WATER ACTIVITY BY BIOSPECKLE LASER resumo.docx
~WRL2593.tmp
QUANDO O RUIDO TORNOU SE INFORMAÇÃO resumo.docx
SÊMEN BOVINO E BIOSPECKLE resumo.pdf.docx
~WRL2864.tmp
~$ANDO O RUIDO TORNOU SE INFORMAÇÃO resumo.docx
Dennis Garbor, Nobel da Física.pdf
DISSERTAÇÃO_Biospeckle PIV (Particle Image Velocimetry) para analisar escoamento de fluidos.pdf
PIV.pdf
Pradille-et-al_AppliedMechanicsMaterials2010.pdf
speckle phase shift.pdf
Fracarolli,JulianaAparecida_M.pdf
UTILIZAÇÃO DO BIOSPECKLE LASER NA AVALIAÇÃO DO POTENCIAL GERMINATIVO DE SEMENTES DE IPÊ ROXO resumo.docx
~WRL0001.tmp
Parametros_Motor_Ind.m
SIEMENS_HEALTHINEERS-right-dose-brochure-02360721.pdf
SIEMENS_HEALTHINEERS_DOSIMETRIAguide-to-right-dose-02475251.pdf
O Bazar dos Sonhos Ruins - Stephen King.pdf
Os Justiceiros - Stephen King.pdf
RESUMO_MEC3F_2020_GABRIELA.docx
TCC aragao.m4a
Livros Fenquim 2
T6 - 1 2020
Gabriela  Moraes's Prática IA.mp4
RELATÓRIO_PARCIAL_IC2020_VOLUNTÁRIA_GABRIELA.docx
PIVICT2020_SERGIO_YOSHINOBU_ARAKI_(CERTIFICADO_233060057382019-33).pdf
PIVICT2020_SERGIO_YOSHIBU_ARAKI_(AVALIACAO_233060057382019-33).docx
PIVICT2020_SERGIO_YOUSHIBU_ARAKI_(RELATORIO_FINAL_233060057382019-33).docx
PIBIFSP2020_DAINEZ(RELATORIOFINAL_2) (1).pdf
LCON2 - EXPERIENCIA 2.docx
PIBIFSP2020_DAINEZ(RELATORIOFINAL_2).pdf
relatorio minhas falas.docx
Comprovante Estagio_Rendimento.pdf
PAP
Boletins notas por semestre - IFSP
AULAS MATLAB
Plano de atividades de estágio_ 2oAno_SiemensHealthcare (editar).pdf
kdq-kbud-cha – 1 de jul. de 2021.pdf
IMG_20210710_175007_862.jpg
IMG_20210710_185541_693.jpg
ATV 04 ECONF LACUNAS ENVIO.gdoc
LELO1-ProfGedeane
96. Desenvolvimento de controle para máquina de indução.xlsx
(PT-BR) CS Solutions Slidedeck HOOD05162003178584_external (1).pptx
(PT-BR) CS Solutions Slidedeck HOOD05162003178584_external.pptx
Manual - Assinatura pelo Adobe Reader.pdf
image014.png
image002.png
image012.png
IAPL0009REV3_SG_ficha de Inscrição Funcionário.xlsx
Manual - Assinatura pelo Adobe Reader.gdoc
Checklist Estagiários - Admissão.xlsx
Formulários e Documentos para admissão_Logicalis Estagiário_ REV1.xlsx
Impr_Ficha_2627036.pdf
Plano de atividades de estágio_ 2oAno_SiemensHealthcare (editar).gdoc
TCE_Gabriela Moraes de Freitas.pdf
TCE_Gabriela Moraes de Freitas.gdoc
35220447960950185156550010003717121010953035.pdf
35220447960950185156550010003717121010953035.gdoc
PA_PLANO DE ATIVIDADES_ GabrielaMoraes.pdf
Pedal em São Roque - 16.07.2022.gmap
Impr_Ficha_2673328.pdf
Impr_Ficha_2681998.pdf
ANEXO_H_RELATORIOS_DE__ATIVIDADES_Periodicidade02_GabrielaMoraes_Relatório02 (1)_signed.pdf
ANEXO_H_RELATORIOS_DE__ATIVIDADES_Periodicidade02_GabrielaMoraes_Relatório01 (1)_signed.pdf
PIBIFSP2020_DAINEZ(RELATORIOFINAL_2).gdoc
20220318_182930.jpg
VID_32740605_181706_133.mp4
20220318_183440.jpg
20220318_181613.jpg
20220318_182946.jpg
20220318_182952.jpg
20220318_211056.jpg
20220318_175729[1].mp4
20220318_194348.jpg
VID_58910328_071408_627.mp4
20220318_191819.jpg
20220318_210957.mp4
20220318_182924.jpg
20220318_174833.jpg
20220318_191947.jpg
20220319_030523_0.jpg
20220318_181616.jpg
20220318_182941.jpg
20220318_181146.jpg
20220318_182956.jpg
IMG-20220318-WA0133.jpeg
20220318_203544.jpg
20220318_183629_02.mp4
20220318_174817.jpg
20220318_183540.jpg
20220318_182943.jpg
20220318_181645.jpg
20220318_191948.jpg
20220318_192914.jpg
20220318_191607.jpg
IMG-20220318-WA0130.jpeg
20220318_183442.jpg
20220318_183434.jpg
20220318_184616.jpg
20220318_183538.jpg
20220318_183629_99.mp4
20220318_184528.mp4
20220318_182841.jpg
20220318_183432.jpg
20220318_181647.jpg
20220318_183539.jpg
20220318_181539.jpg
20220318_180053.mp4
20220318_191915.jpg
20220318_190900.jpg
20220318_180530[1].mp4
20220318_054726_0.jpg
20220318_174832.jpg
20220318_181339.jpg
20220318_192231.jpg
20220318_205401.jpg
20220318_211406.jpg
VID_58580318_161309_129.mp4
20220318_175958.mp4
VID_32740927_171129_011.mp4
20220318_191843.jpg
20220318_174826.jpg
20220318_190935.jpg
20220318_183446.jpg
20220318_191846.jpg
20220318_205409.jpg
IMG-20220318-WA0097.jpeg
20220318_191807.jpg
20220318_211408.jpg
20220318_191811.jpg
VID_32730611_173221_040.mp4
20220318_182850.jpg
20220318_183619.jpg
20220318_211051.jpg
VID-20220318-WA0157.mp4
20220318_071259_0.jpg
20220318_183629_01.mp4
20220318_181610.jpg
20220318_192916.jpg
20220318_192915.jpg
20220318_065806_0.jpg
20220318_181328.jpg
IMG-20220318-WA0135.jpeg
20220318_205405.jpg
20220318_181615.jpg
20220318_194346.jpg
20220318_205359.jpg
20220318_183443.jpg
VID_32730312_115910_584.mp4
20220318_191918.jpg
IMG-20220318-WA0137.jpeg
20220318_205612.mp4
20220318_195611.jpg
20220318_181341.jpg
20220318_181338.jpg
20220318_181537.jpg
20220318_182848.jpg
20220318_183954[1].mp4
20220318_181617.jpg
20220318_183546.jpg
20220318_183542.jpg
20220318_191840.jpg
20220318_205700.mp4
20220318_174836.jpg
20220318_190937.jpg
20220318_181333.jpg
20220318_192941.jpg
20220318_184610.jpg
IMG_20220318_211923_675.webp
20220318_190939.jpg
VID_58880315_154917_153.mp4
20220318_192943.jpg
20220318_205326.jpg
20220318_191922.jpg
20220318_182953.jpg
20220318_174827.jpg
20220318_182954.jpg
20220318_195602.jpg
20220318_183543.jpg
20220318_174607.jpg
20220318_210915.mp4
TCC 2023
1. Certificações
IC Biospeckle
IC Motor de Indução
Gabriela_Moraes_de_Freitas___Currículo_WRIT.pdf
Fotos da formatura
2023_01_Fotos
2023_02_Fotos_Bertioga
Example.Learning Log: Think about data in daily life.gdoc
Media.jpg
DA C1M1 Learning Log Consider how data analysts approach tasks_pt.gdoc
Colab Notebooks
Fotos Bike
Grupo 2 - Carta ao CEO - Reprograma.gslides
20250316_154250.jpg
20250316_154341.jpg
20250316_154410.jpg
20250316_154658.jpg
20250316_154723 (1).jpg
20250316_154738 (1).jpg
20250316_155850.jpg
20250316_155917.jpg
20250316_160242.jpg
20250316_160257.jpg
20250316_160309.jpg
20250316_160312.jpg
20250316_160357.jpg
20250316_160618.jpg
20250316_160627.jpg
20250316_160635.jpg
20250316_160729.jpg
20250316_160743.jpg
20250316_160756.jpg
20250316_160830.jpg
20250316_160844.jpg
20250316_160906.jpg
20250316_160959.jpg
20250316_161004.jpg
20250316_161023.jpg
20250316_161033.jpg
20250316_161053.jpg
20250316_161152.jpg
20250316_161205.jpg
20250316_161235.jpg
20250316_161247.jpg
20250316_161252.jpg
20250316_161310.jpg
20250316_161457.jpg
20250316_161506.jpg
20250316_161523.jpg
20250316_161528.jpg
20250316_161633.jpg
20250316_161816.jpg
20250316_161843.jpg
20250316_161904.jpg
20250316_161915.jpg
20250316_162035.jpg
20250316_162056.jpg
20250316_162111.jpg
20250316_162223.jpg
20250316_162327.jpg
20250316_162340.jpg
20250316_162539.jpg
20250316_162550.jpg
20250316_171551.jpg
20250316_171553.jpg
20250316_171617.jpg
20250316_171647.jpg
20250316_171702.jpg
20250316_171712.jpg
20250316_171718.jpg
20250316_171901.jpg
20250316_171904.jpg
20250316_171916.jpg
20250316_171926.jpg
20250316_171927.jpg
20250316_171950.jpg
20250316_172003.jpg
20250316_172013.jpg
20250316_173539.jpg
20250316_173543.jpg
20250316_173623.jpg
20250316_173633.jpg
20250316_173700.jpg
20250316_173703.jpg
20250316_173726.jpg
20250316_173737.jpg
20250316_173750.jpg
20250316_173754.jpg
20250316_173938.jpg
20250316_173947.jpg
20250316_173959.jpg
20250316_174030.jpg
20250316_174038.jpg
20250316_174053.jpg
20250316_174247.jpg
20250316_174255.jpg
20250316_174306.jpg
20250316_174338.jpg
20250316_174345.jpg
20250316_174604.jpg
20250316_174616.jpg
20250316_174617.jpg
20250316_174646.jpg
20250316_174653.jpg
20250316_174704.jpg
20250316_174707.jpg
20250316_174911.jpg
20250316_174930.jpg
20250316_174931.jpg
20250316_175003.jpg
20250316_175010.jpg
20250316_175209.jpg
20250316_175211.jpg
20250316_175243.jpg
20250316_175314.jpg
20250316_175351.jpg
20250316_175351(0).jpg
20250316_175357.jpg
20250316_175410.jpg
20250316_175708.jpg
20250316_175716.jpg
20250316_175724.jpg
20250316_175814.jpg
20250316_175820.jpg
20250316_175833.jpg
20250316_180129.jpg
20250316_180156.jpg
20250316_180216.jpg
20250316_180222.jpg
20250316_180310.jpg
20250316_180312.jpg
20250316_180340.jpg
20250316_180348.jpg
20250316_180423.jpg
20250316_180426.jpg
20250316_154723.jpg
20250316_154738.jpg
20250316_154835.jpg
20250316_154906.jpg
20250316_154912.jpg
20250316_154938.jpg
20250316_155406.jpg
20250316_155423.jpg
20250316_155440.jpg
20250316_155631.jpg
20250316_155641.jpg
20250316_155656.jpg
20250316_160012.jpg
20250316_160036.jpg
20250316_160101.jpg
20250316_160141.jpg
20250316_160426.jpg
20250316_160509.jpg
20250316_160522.jpg
20250316_160605.jpg
Skate para Elas - EMEF Irmã Dulce
Arquivos Celular pre Lady Gaga
Viagem FOZ Pai<3
Pré Lady Gaga fotos
FICHA CADASTRAL (2).docx
FICHA CADASTRAL (1).docx
FICHA CADASTRAL.docx
Erro_ADATech.png
Curriculum_Vitae_GabrielaMoraesdeFreitas (1).pdf
Boleto_1774009874838.pdf
Foto de Gabi Moraes
IMG-20260224-WA0027(2).jpg

In [ ]:
import os # Importa o módulo 'os' para interagir com o sistema operacional.

# Define o caminho para o diretório 'Consumo inteligente hackathon' dentro do Google Drive.
cons_path = '/content/drive/MyDrive/Consumo inteligente hackathon'

# Verifica se o caminho do diretório existe.
if os.path.exists(cons_path):
    print(f"Conteúdo de {cons_path}:")
    # Lista e imprime o conteúdo do diretório.
    for item in os.listdir(cons_path):
        print(item)
else:
    print(f"O caminho {cons_path} não foi encontrado. Por favor, certifique-se de que o diretório existe.")

O caminho /content/drive/MyDrive/Consumo inteligente hackathon não foi encontrado. Por favor, certifique-se de que o diretório existe.

In [ ]:
import os

# List the contents of the 'data' directory within 'Consumo inteligente hackathon'
data_path = '/content/drive/MyDrive/Consumo inteligente hackathon/data'

if os.path.exists(data_path):
    print(f"Contents of {data_path}:")
    for item in os.listdir(data_path):
        print(item)
else:
    print(f"The path {data_path} was not found. Please ensure the directory exists.")

The path /content/drive/MyDrive/Consumo inteligente hackathon/data was not found. Please ensure the directory exists.

In [ ]:
df=pd.read_excel("/content/drive/MyDrive/Consumo inteligente hackathon/data/raw _dados originais /Online_Retail.xlsx",engine="openpyxl")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Consumo inteligente hackathon/data/raw _dados originais /Online_Retail.xlsx'

In [ ]:
import os

drive_path = "/content/drive/MyDrive/Consumo inteligente hackathon/data/raw _dados originais /"

# Listar o conteúdo do diretório
if os.path.exists(drive_path):
    print(f"Conteúdo de {drive_path}:")
    for item in os.listdir(drive_path):
        print(item)
else:
    print(f"O caminho {drive_path} não foi encontrado. Verifique se o Google Drive está montado corretamente e se o caminho está certo.")

Conteúdo de /content/drive/MyDrive/Consumo inteligente hackathon/data/raw _dados originais /:
Online_Retail.xlsx

In [ ]:
#Carregando Dataset
import pandas as pd
df = pd.read_excel("/content/drive/MyDrive/Consumo inteligente hackathon/data/raw _dados originais /Online_Retail.xlsx",engine="openpyxl")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
#Dimensão do Dataset
print("Linhas e Colunas:",df.shape)

Linhas e Colunas: (541909, 8)

In [ ]:
# Informações gerais
df.info( )

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [ ]:
#Verificando valores nulos
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
#Estatísticas Basicas
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [ ]:
#Verificação de duplicados
print("Duplicados",df.duplicated().sum())

Duplicados 5268

In [ ]:
#Limpeza inicial
df_clean=df.copy( )

df_clean=df_clean.dropna(subset=["CustomerID"] )
df_clean=df_clean[df_clean["Quantity"]>0]
df_clean=df_clean[df_clean["UnitPrice"]>0]

print("Dataset após limpeza:",df_clean.shape)
df_clean.head()

Dataset após limpeza: (397884, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
#Converte data
df_clean["InvoiceDate"]=pd.to_datetime(df_clean["InvoiceDate"])
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.3+ MB

In [ ]:
#Criando Coluna de valor total
df_clean["TotalValue"]=df_clean["Quantity"]*df_clean["UnitPrice"]
df_clean.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalValue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34

In [ ]:
#Criando colunas auxiliares

df_clean["Month"]=df_clean["InvoiceDate"].dt.to_period("M").astype(str)
df_clean["DayOfWeek"]=df_clean["InvoiceDate"].dt.day_name()
df_clean["Hour"]=df_clean["InvoiceDate"].dt.hour
df_clean["Day"]=df_clean["InvoiceDate"].dt.day

df_clean.head( )

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalValue,Month,DayOfWeek,Hour,Day
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010-12,Wednesday,8,1
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12,Wednesday,8,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010-12,Wednesday,8,1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12,Wednesday,8,1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010-12,Wednesday,8,1

In [ ]:
#Resultado final
df_clean.info()
df_clean.describe( )

<class 'pandas.core.frame.DataFrame'>
Index: 397884 entries, 0 to 541908
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    397884 non-null  object
 1   StockCode    397884 non-null  object
 2   Description  397884 non-null  object
 3   Quantity     397884 non-null  int64
 4   InvoiceDate  397884 non-null  datetime64[ns]
 5   UnitPrice    397884 non-null  float64
 6   CustomerID   397884 non-null  float64
 7   Country      397884 non-null  object
 8   TotalValue   397884 non-null  float64
 9   Month        397884 non-null  object
 10  DayOfWeek    397884 non-null  object
 11  Hour         397884 non-null  int32
 12  Day          397884 non-null  int32
dtypes: datetime64[ns](1), float64(3), int32(2), int64(1), object(6)
memory usage: 39.5+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID,TotalValue,Hour,Day
count,397884.000000,397884,397884.000000,397884.000000,397884.000000,397884.000000,397884.000000
mean,12.988238,2011-07-10 23:41:23.511023360,3.116488,15294.423453,22.397000,12.728202,15.042186
min,1.000000,2010-12-01 08:26:00,0.001000,12346.000000,0.001000,6.000000,1.000000
25%,2.000000,2011-04-07 11:12:00,1.250000,13969.000000,4.680000,11.000000,7.000000
50%,6.000000,2011-07-31 14:39:00,1.950000,15159.000000,11.800000,13.000000,15.000000
75%,12.000000,2011-10-20 14:33:00,3.750000,16795.000000,19.800000,14.000000,22.000000
max,80995.000000,2011-12-09 12:50:00,8142.750000,18287.000000,168469.600000,20.000000,31.000000
std,179.331775,NaN,22.097877,1713.141560,309.071041,2.273519,8.653746

In [ ]:
#Salvando dataset tratado em CSV no Google Drive
output_path = '/content/drive/MyDrive/Consumo inteligente hackathon/data/processed dados tratados/Online_Retail_clean.csv'
df_clean.to_csv(output_path, index=False)
print(f"Arquivo salvo em: {output_path}")

NameError: name 'df_clean' is not defined

##Notebook 01 - Limpeza e Preparação do Dataset (Online Retail/ Keggle/UCI).
Este notebook realiza o carregamento, inspeção, limpeza e preparação dos dados para análise exploratória,SQL e Machine Learning.
## OBJETIVO
_ Carregar o dataset Online Retail
_ Tratar valores nulos e inconstencias
_ Verificar estrutura e qualidade dos dados
_ Criar colunas auxiliares para analises
_ Explorar dataset limpo para as proximas etapas do projeto
## DESCRIÇÃO DO DATASET
Fonte: Online Retail Dataset (UCI Repository)
Principais colunas : InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerlD,Country.
## Etapas executadas neste notebook
1. Importação  e leitura do dataset
2. Inspeção inicial
3. Limpeza e tratamento
4. Criação de novas colunas
5. Exportação do dataset tratado